Repository Caleydo/tourdino, pull requests merged in 2020-03, with the labels that each got.

#20 Make column/row highlighting work for Ordino
  src/Measures.ts
  src/TouringPanel.ts
  src/tasks/Tasks.ts
Labels: release: minor, type: bug

#18 Make touring panel work for large data sets
  src/Managers.ts
  src/Measures.ts
  src/RankingAdapter.ts
  src/TouringPanel.ts
  src/Workers/AdjRandRandom.ts
  src/Workers/EnrichmentScorePermutation.ts
  src/Workers/JaccardRandom.ts
  src/Workers/WorkerManager.ts
  src/measure_visualization/BoxPlot.ts
  src/measure_visualization/GroupedBarChart.ts
  src/measure_visualization/LineChart.ts
  src/measure_visualization/ParallelSets.ts
  src/measure_visualization/ScatterPlot.ts
  src/phovea.ts
  src/style.scss
  src/tasks/Tasks.ts
  src/util.ts
Labels: release: minor, type: refactor

#30 Update to Typescript 3.8
  package.json
Labels: priority: high, release: major, type: refactor

#35 Remove isNaN() check when checking if array isArrayOfNumbers()
  src/Measures.ts
Labels: release: patch, type: bug

#38 Further performace improvements
  src/RankingAdapter.ts
Labels: release: minor, type: refactor

#37 Use accessor as ID to identify scores
  src/RankingAdapter.ts
Labels: release: minor, type: bug

#39 Update dependencies
  package.json
Labels: priority: medium, type: refactor

#44 Refactor the TouringPanel to match PanelTab extension point
  package.json
  src/TouringPanel.ts
Labels: release: minor, type: refactor

#41 Add ES5 accessor string in `isProxyAccessor`
  package.json
  src/RankingAdapter.ts
  src/util.ts
Labels: priority: high, release: patch, type: bug

#43 Change `buildId` to `JSON.stringify(buildId)`
  webpack.config.js
Labels: priority: medium, type: refactor

#46 Enable gif files
  tsd.d.ts
  webpack.config.js
Labels: type: refactor
